version: "2"
services:
  service-vehicle-robot:
    image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
    labels:
      base_path: /vehicle-robot
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: "true"
      lb.g7pay.expose80: /vehicle-robot
      project.description: ${PROJECT_DESCRIPTION}
      project.group: ${PROJECT_GROUP}
      project.name: ${PROJECT_NAME}
      project.version: ${PROJECT_VERSION}
      upstreams: ${S_CLIENTID_HOST},robot.db-routers.rancher.internal,robot-readonly.db-routers.rancher.internal
    environment:
      GOENV: ${GOENV}
      S_CLIENTID_HOST: ${S_CLIENTID_HOST}
      S_COCOMODEL_LABELPATH: ${S_COCOMODEL_LABELPATH}
      S_COCOMODEL_MODELPATH: ${S_COCOMODEL_MODELPATH}
      S_CONFIGAGENT_HOST: ${S_CONFIGAGENT_HOST}
      S_CONFIGAGENT_MODE: ${S_CONFIGAGENT_MODE}
      S_CONFIGAGENT_PORT: ${S_CONFIGAGENT_PORT}
      S_CONFIGAGENT_PULLCONFIGINTERVAL: ${S_CONFIGAGENT_PULLCONFIGINTERVAL}
      S_CONFIGAGENT_STACKID: ${S_CONFIGAGENT_STACKID}
      S_CONFIGAGENT_TIMEOUT: ${S_CONFIGAGENT_TIMEOUT}
      S_LOG_LEVEL: ${S_LOG_LEVEL}
      S_MASTERDB_PASSWORD: ${S_MASTERDB_PASSWORD}
      S_MASTERDB_USER: ${S_MASTERDB_USER}
      S_SERVETELEPORT_COUNTTIME: ${S_SERVETELEPORT_COUNTTIME}
      S_SERVETELEPORT_DEFAULTBODYCODEC: ${S_SERVETELEPORT_DEFAULTBODYCODEC}
      S_SERVETELEPORT_DEFAULTCONTEXTAGE: ${S_SERVETELEPORT_DEFAULTCONTEXTAGE}
      S_SERVETELEPORT_DEFAULTDIALTIMEOUT: ${S_SERVETELEPORT_DEFAULTDIALTIMEOUT}
      S_SERVETELEPORT_DEFAULTSESSIONAGE: ${S_SERVETELEPORT_DEFAULTSESSIONAGE}
      S_SERVETELEPORT_IP: ${S_SERVETELEPORT_IP}
      S_SERVETELEPORT_NETWORK: ${S_SERVETELEPORT_NETWORK}
      S_SERVETELEPORT_PORT: ${S_SERVETELEPORT_PORT}
      S_SERVETELEPORT_PRINTDETAIL: ${S_SERVETELEPORT_PRINTDETAIL}
      S_SERVETELEPORT_REDIALINTERVAL: ${S_SERVETELEPORT_REDIALINTERVAL}
      S_SERVETELEPORT_REDIALTIMES: ${S_SERVETELEPORT_REDIALTIMES}
      S_SERVETELEPORT_SLOWCOMETDURATION: ${S_SERVETELEPORT_SLOWCOMETDURATION}
      S_SLAVEDB_PASSWORD: ${S_SLAVEDB_PASSWORD}
      S_SLAVEDB_USER: ${S_SLAVEDB_USER}
    dns_search:
    - rancher.internal
    dns:
    - 169.254.169.250
