from: ${PROFZONE_DOCKER_REGISTRY}/profzone/golang:runtime
image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
workdir: /go/bin
env:
  GOENV: DEV
  S_CLIENTID_HOST: service-id.robot.rancher.internal
  S_CLIENTID_PORT: "80"
  S_CONFIGAGENT_HOST: service-configurations.profzone.rancher.internal
  S_CONFIGAGENT_MODE: http
  S_CONFIGAGENT_PORT: "80"
  S_CONFIGAGENT_PULLCONFIGINTERVAL: "60"
  S_CONFIGAGENT_STACKID: "0"
  S_CONFIGAGENT_TIMEOUT: "5"
  S_LOG_FORMAT: json
  S_MASTERDB_HOST: robot.db-routers.rancher.internal
  S_MASTERDB_PORT: "3306"
  S_SERVERGRPC_PORT: "999"
  S_SERVERHTTP_PORT: "80"
  S_SERVERHTTP_WITHCORS: "false"
  S_SLAVEDB_HOST: robot-readonly.db-routers.rancher.internal
  S_SLAVEDB_PORT: "3306"
add:
  ./config: ./config
  ./profzone.yml: ./
  ./service-vehicle-robot: ./
  ./swagger.json: ./
expose:
- "80"
cmd:
- ./service-vehicle-robot
- -c=false
